"""
app/models/user.py
==================
ORM model for the `users` table.

A User is the root identity entity. Every other entity in the system
(TravelProfile, Trip) is owned by a User via foreign key relationships.

Relationships
-------------
- user.travel_profile  → TravelProfile (one-to-one, lazy loaded)
- user.trips           → list[Trip]    (one-to-many, lazy loaded)
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import Index, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, generate_uuid

if TYPE_CHECKING:
    # Imported only for type checking to avoid circular imports at runtime.
    from app.models.travel_profile import TravelProfile
    from app.models.trip import Trip


class User(Base, TimestampMixin):
    """
    Represents a registered Roamio user.

    The `email` column is the human-facing unique identifier.
    The `hashed_password` column stores a bcrypt hash — the plaintext
    password is never persisted (auth logic handled in Milestone 4).
    """

    __tablename__ = "users"

    # -------------------------------------------------------------------------
    # Primary key
    # -------------------------------------------------------------------------
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=generate_uuid,
        doc="UUID v4 primary key. Generated by the application layer.",
    )

    # -------------------------------------------------------------------------
    # Identity fields
    # -------------------------------------------------------------------------
    email: Mapped[str] = mapped_column(
        String(320),        # RFC 5321 max email length
        unique=True,
        nullable=False,
        index=True,         # Fast lookups during login
        doc="User's email address. Must be unique across all accounts.",
    )

    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="bcrypt hash of the user's password. Plaintext is never stored.",
    )

    # -------------------------------------------------------------------------
    # Relationships
    # -------------------------------------------------------------------------
    travel_profile: Mapped[TravelProfile | None] = relationship(
        "TravelProfile",
        back_populates="user",
        uselist=False,          # one-to-one: User has exactly one TravelProfile
        cascade="all, delete-orphan",
        doc="The user's persistent travel preferences profile.",
    )

    trips: Mapped[list[Trip]] = relationship(
        "Trip",
        back_populates="user",
        cascade="all, delete-orphan",
        doc="All trips generated by this user, ordered by the query layer.",
    )

    # -------------------------------------------------------------------------
    # Indexes
    # -------------------------------------------------------------------------
    __table_args__ = (
        Index("ix_users_email", "email"),   # redundant with index=True above
    )                                        # but explicit for Alembic clarity

    def __repr__(self) -> str:
        return f"<User id={self.id!r} email={self.email!r}>"
