version: "3.9"

services:
  roamio-db:
    image: postgres:15
    container_name: roamio-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: roamio_db
      POSTGRES_USER: roamio_user
      POSTGRES_PASSWORD: roamio_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roamio_user -d roamio_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  roamio-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: roamio-api

    depends_on:
      roamio-db:
        condition: service_healthy

    env_file:
      - ../.env

    ports:
      - "8000:8000"

    restart: unless-stopped

volumes:
  postgres_data: